/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../pages/__root'
import { Route as adminLayoutRouteImport } from './../../pages/(admin)/layout'
import { Route as IndexRouteImport } from './../../pages/index'
import { Route as errors500RouteImport } from './../../pages/(errors)/500'
import { Route as errors404RouteImport } from './../../pages/(errors)/404'
import { Route as errors403RouteImport } from './../../pages/(errors)/403'
import { Route as authLoginOutRouteImport } from './../../pages/(auth)/login-out'
import { Route as adminUserCenterRouteImport } from './../../pages/(admin)/user-center'
import { Route as authLoginLayoutRouteImport } from './../../pages/(auth)/login/layout'
import { Route as adminHomeLayoutRouteImport } from './../../pages/(admin)/home/layout'
import { Route as adminpersonnelLayoutRouteImport } from './../../pages/(admin)/(personnel)/layout'
import { Route as admindevelopmentAndPerformanceLayoutRouteImport } from './../../pages/(admin)/(developmentAndPerformance)/layout'
import { Route as admindailyLayoutRouteImport } from './../../pages/(admin)/(daily)/layout'
import { Route as adminanalysisAndSettingLayoutRouteImport } from './../../pages/(admin)/(analysisAndSetting)/layout'
import { Route as authLoginIndexRouteImport } from './../../pages/(auth)/login/index'
import { Route as authLoginResetPwdRouteImport } from './../../pages/(auth)/login/reset-pwd'
import { Route as authLoginRegisterRouteImport } from './../../pages/(auth)/login/register'
import { Route as authLoginCodeLoginRouteImport } from './../../pages/(auth)/login/code-login'
import { Route as adminanalysisAndSettingSettingsRouteImport } from './../../pages/(admin)/(analysisAndSetting)/settings'
import { Route as adminanalysisAndSettingReportsRouteImport } from './../../pages/(admin)/(analysisAndSetting)/reports'
import { Route as adminanalysisAndSettingNotificationsRouteImport } from './../../pages/(admin)/(analysisAndSetting)/notifications'
import { Route as adminpersonnelOrganizationLayoutRouteImport } from './../../pages/(admin)/(personnel)/organization/layout'
import { Route as adminpersonnelEmployeesLayoutRouteImport } from './../../pages/(admin)/(personnel)/employees/layout'
import { Route as admindevelopmentAndPerformanceTrainingLayoutRouteImport } from './../../pages/(admin)/(developmentAndPerformance)/training/layout'
import { Route as admindevelopmentAndPerformancePerformanceLayoutRouteImport } from './../../pages/(admin)/(developmentAndPerformance)/performance/layout'
import { Route as admindailyPayrollLayoutRouteImport } from './../../pages/(admin)/(daily)/payroll/layout'
import { Route as admindailyAttendanceLayoutRouteImport } from './../../pages/(admin)/(daily)/attendance/layout'
import { Route as adminBuiltinIframePageUrlRouteImport } from './../../pages/(admin)/_builtin/iframe-page/$url'
import { Route as adminpersonnelOrganizationRolesRouteImport } from './../../pages/(admin)/(personnel)/organization/roles'
import { Route as adminpersonnelOrganizationDepartmentsRouteImport } from './../../pages/(admin)/(personnel)/organization/departments'
import { Route as adminpersonnelOrganizationChartRouteImport } from './../../pages/(admin)/(personnel)/organization/chart'
import { Route as adminpersonnelEmployeesOnboardingRouteImport } from './../../pages/(admin)/(personnel)/employees/onboarding'
import { Route as adminpersonnelEmployeesOffboardingRouteImport } from './../../pages/(admin)/(personnel)/employees/offboarding'
import { Route as adminpersonnelEmployeesMaterialRouteImport } from './../../pages/(admin)/(personnel)/employees/material'
import { Route as admindevelopmentAndPerformanceTrainingRecordsRouteImport } from './../../pages/(admin)/(developmentAndPerformance)/training/records'
import { Route as admindevelopmentAndPerformanceTrainingPlansRouteImport } from './../../pages/(admin)/(developmentAndPerformance)/training/plans'
import { Route as admindevelopmentAndPerformancePerformancePlansRouteImport } from './../../pages/(admin)/(developmentAndPerformance)/performance/plans'
import { Route as admindevelopmentAndPerformancePerformanceEvaluationRouteImport } from './../../pages/(admin)/(developmentAndPerformance)/performance/evaluation'
import { Route as admindailyPayrollDistributeRouteImport } from './../../pages/(admin)/(daily)/payroll/distribute'
import { Route as admindailyPayrollCalculateRouteImport } from './../../pages/(admin)/(daily)/payroll/calculate'
import { Route as admindailyPayrollBonusPenaltyRouteImport } from './../../pages/(admin)/(daily)/payroll/bonus-penalty'
import { Route as admindailyAttendanceOvertimeRouteImport } from './../../pages/(admin)/(daily)/attendance/overtime'
import { Route as admindailyAttendanceLeaveRouteImport } from './../../pages/(admin)/(daily)/attendance/leave'
import { Route as admindailyAttendanceClockInRouteImport } from './../../pages/(admin)/(daily)/attendance/clock-in'
import { Route as admindailyAttendanceRecordsIndexRouteImport } from './../../pages/(admin)/(daily)/attendance/records/index'
import { Route as admindailyAttendanceApprovalIndexRouteImport } from './../../pages/(admin)/(daily)/attendance/approval/index'
import { Route as admindailyAttendanceRecordsMonthlyRouteImport } from './../../pages/(admin)/(daily)/attendance/records/monthly'
import { Route as admindailyAttendanceLeaveLeaveIdRouteImport } from './../../pages/(admin)/(daily)/attendance/leave.$leaveId'
import { Route as admindailyAttendanceApprovalApprovalIdRouteImport } from './../../pages/(admin)/(daily)/attendance/approval/$approvalId'
import { Route as admindailyAttendanceApprovalRulesNewRouteImport } from './../../pages/(admin)/(daily)/attendance/approval/rules.new'
import { Route as admindailyAttendanceApprovalRulesRuleIdRouteImport } from './../../pages/(admin)/(daily)/attendance/approval/rules.$ruleId'
import { Route as admindailyAttendanceApprovalRulesRuleIdEditRouteImport } from './../../pages/(admin)/(daily)/attendance/approval/rules.$ruleId.edit'

const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginOutRoute = authLoginOutRouteImport.update({
  id: '/(auth)/login-out',
  path: '/login-out',
  getParentRoute: () => rootRouteImport,
} as any)
const adminUserCenterRoute = adminUserCenterRouteImport.update({
  id: '/user-center',
  path: '/user-center',
  getParentRoute: () => adminLayoutRoute,
} as any)
const authLoginLayoutRoute = authLoginLayoutRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const adminHomeLayoutRoute = adminHomeLayoutRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminpersonnelLayoutRoute = adminpersonnelLayoutRouteImport.update({
  id: '/(personnel)',
  getParentRoute: () => adminLayoutRoute,
} as any)
const admindevelopmentAndPerformanceLayoutRoute =
  admindevelopmentAndPerformanceLayoutRouteImport.update({
    id: '/(developmentAndPerformance)',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const admindailyLayoutRoute = admindailyLayoutRouteImport.update({
  id: '/(daily)',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminanalysisAndSettingLayoutRoute =
  adminanalysisAndSettingLayoutRouteImport.update({
    id: '/(analysisAndSetting)',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const authLoginResetPwdRoute = authLoginResetPwdRouteImport.update({
  id: '/reset-pwd',
  path: '/reset-pwd',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const authLoginRegisterRoute = authLoginRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const authLoginCodeLoginRoute = authLoginCodeLoginRouteImport.update({
  id: '/code-login',
  path: '/code-login',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const adminanalysisAndSettingSettingsRoute =
  adminanalysisAndSettingSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => adminanalysisAndSettingLayoutRoute,
  } as any)
const adminanalysisAndSettingReportsRoute =
  adminanalysisAndSettingReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => adminanalysisAndSettingLayoutRoute,
  } as any)
const adminanalysisAndSettingNotificationsRoute =
  adminanalysisAndSettingNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => adminanalysisAndSettingLayoutRoute,
  } as any)
const adminpersonnelOrganizationLayoutRoute =
  adminpersonnelOrganizationLayoutRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => adminpersonnelLayoutRoute,
  } as any)
const adminpersonnelEmployeesLayoutRoute =
  adminpersonnelEmployeesLayoutRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => adminpersonnelLayoutRoute,
  } as any)
const admindevelopmentAndPerformanceTrainingLayoutRoute =
  admindevelopmentAndPerformanceTrainingLayoutRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => admindevelopmentAndPerformanceLayoutRoute,
  } as any)
const admindevelopmentAndPerformancePerformanceLayoutRoute =
  admindevelopmentAndPerformancePerformanceLayoutRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => admindevelopmentAndPerformanceLayoutRoute,
  } as any)
const admindailyPayrollLayoutRoute = admindailyPayrollLayoutRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => admindailyLayoutRoute,
} as any)
const admindailyAttendanceLayoutRoute =
  admindailyAttendanceLayoutRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => admindailyLayoutRoute,
  } as any)
const adminBuiltinIframePageUrlRoute =
  adminBuiltinIframePageUrlRouteImport.update({
    id: '/_builtin/iframe-page/$url',
    path: '/iframe-page/$url',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminpersonnelOrganizationRolesRoute =
  adminpersonnelOrganizationRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => adminpersonnelOrganizationLayoutRoute,
  } as any)
const adminpersonnelOrganizationDepartmentsRoute =
  adminpersonnelOrganizationDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => adminpersonnelOrganizationLayoutRoute,
  } as any)
const adminpersonnelOrganizationChartRoute =
  adminpersonnelOrganizationChartRouteImport.update({
    id: '/chart',
    path: '/chart',
    getParentRoute: () => adminpersonnelOrganizationLayoutRoute,
  } as any)
const adminpersonnelEmployeesOnboardingRoute =
  adminpersonnelEmployeesOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => adminpersonnelEmployeesLayoutRoute,
  } as any)
const adminpersonnelEmployeesOffboardingRoute =
  adminpersonnelEmployeesOffboardingRouteImport.update({
    id: '/offboarding',
    path: '/offboarding',
    getParentRoute: () => adminpersonnelEmployeesLayoutRoute,
  } as any)
const adminpersonnelEmployeesMaterialRoute =
  adminpersonnelEmployeesMaterialRouteImport.update({
    id: '/material',
    path: '/material',
    getParentRoute: () => adminpersonnelEmployeesLayoutRoute,
  } as any)
const admindevelopmentAndPerformanceTrainingRecordsRoute =
  admindevelopmentAndPerformanceTrainingRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => admindevelopmentAndPerformanceTrainingLayoutRoute,
  } as any)
const admindevelopmentAndPerformanceTrainingPlansRoute =
  admindevelopmentAndPerformanceTrainingPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => admindevelopmentAndPerformanceTrainingLayoutRoute,
  } as any)
const admindevelopmentAndPerformancePerformancePlansRoute =
  admindevelopmentAndPerformancePerformancePlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => admindevelopmentAndPerformancePerformanceLayoutRoute,
  } as any)
const admindevelopmentAndPerformancePerformanceEvaluationRoute =
  admindevelopmentAndPerformancePerformanceEvaluationRouteImport.update({
    id: '/evaluation',
    path: '/evaluation',
    getParentRoute: () => admindevelopmentAndPerformancePerformanceLayoutRoute,
  } as any)
const admindailyPayrollDistributeRoute =
  admindailyPayrollDistributeRouteImport.update({
    id: '/distribute',
    path: '/distribute',
    getParentRoute: () => admindailyPayrollLayoutRoute,
  } as any)
const admindailyPayrollCalculateRoute =
  admindailyPayrollCalculateRouteImport.update({
    id: '/calculate',
    path: '/calculate',
    getParentRoute: () => admindailyPayrollLayoutRoute,
  } as any)
const admindailyPayrollBonusPenaltyRoute =
  admindailyPayrollBonusPenaltyRouteImport.update({
    id: '/bonus-penalty',
    path: '/bonus-penalty',
    getParentRoute: () => admindailyPayrollLayoutRoute,
  } as any)
const admindailyAttendanceOvertimeRoute =
  admindailyAttendanceOvertimeRouteImport.update({
    id: '/overtime',
    path: '/overtime',
    getParentRoute: () => admindailyAttendanceLayoutRoute,
  } as any)
const admindailyAttendanceLeaveRoute =
  admindailyAttendanceLeaveRouteImport.update({
    id: '/leave',
    path: '/leave',
    getParentRoute: () => admindailyAttendanceLayoutRoute,
  } as any)
const admindailyAttendanceClockInRoute =
  admindailyAttendanceClockInRouteImport.update({
    id: '/clock-in',
    path: '/clock-in',
    getParentRoute: () => admindailyAttendanceLayoutRoute,
  } as any)
const admindailyAttendanceRecordsIndexRoute =
  admindailyAttendanceRecordsIndexRouteImport.update({
    id: '/records/',
    path: '/records/',
    getParentRoute: () => admindailyAttendanceLayoutRoute,
  } as any)
const admindailyAttendanceApprovalIndexRoute =
  admindailyAttendanceApprovalIndexRouteImport.update({
    id: '/approval/',
    path: '/approval/',
    getParentRoute: () => admindailyAttendanceLayoutRoute,
  } as any)
const admindailyAttendanceRecordsMonthlyRoute =
  admindailyAttendanceRecordsMonthlyRouteImport.update({
    id: '/records/monthly',
    path: '/records/monthly',
    getParentRoute: () => admindailyAttendanceLayoutRoute,
  } as any)
const admindailyAttendanceLeaveLeaveIdRoute =
  admindailyAttendanceLeaveLeaveIdRouteImport.update({
    id: '/$leaveId',
    path: '/$leaveId',
    getParentRoute: () => admindailyAttendanceLeaveRoute,
  } as any)
const admindailyAttendanceApprovalApprovalIdRoute =
  admindailyAttendanceApprovalApprovalIdRouteImport.update({
    id: '/approval/$approvalId',
    path: '/approval/$approvalId',
    getParentRoute: () => admindailyAttendanceLayoutRoute,
  } as any)
const admindailyAttendanceApprovalRulesNewRoute =
  admindailyAttendanceApprovalRulesNewRouteImport.update({
    id: '/approval/rules/new',
    path: '/approval/rules/new',
    getParentRoute: () => admindailyAttendanceLayoutRoute,
  } as any)
const admindailyAttendanceApprovalRulesRuleIdRoute =
  admindailyAttendanceApprovalRulesRuleIdRouteImport.update({
    id: '/approval/rules/$ruleId',
    path: '/approval/rules/$ruleId',
    getParentRoute: () => admindailyAttendanceLayoutRoute,
  } as any)
const admindailyAttendanceApprovalRulesRuleIdEditRoute =
  admindailyAttendanceApprovalRulesRuleIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => admindailyAttendanceApprovalRulesRuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof adminHomeLayoutRoute
  '/login': typeof authLoginLayoutRouteWithChildren
  '/user-center': typeof adminUserCenterRoute
  '/login-out': typeof authLoginOutRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/attendance': typeof admindailyAttendanceLayoutRouteWithChildren
  '/payroll': typeof admindailyPayrollLayoutRouteWithChildren
  '/performance': typeof admindevelopmentAndPerformancePerformanceLayoutRouteWithChildren
  '/training': typeof admindevelopmentAndPerformanceTrainingLayoutRouteWithChildren
  '/employees': typeof adminpersonnelEmployeesLayoutRouteWithChildren
  '/organization': typeof adminpersonnelOrganizationLayoutRouteWithChildren
  '/notifications': typeof adminanalysisAndSettingNotificationsRoute
  '/reports': typeof adminanalysisAndSettingReportsRoute
  '/settings': typeof adminanalysisAndSettingSettingsRoute
  '/login/code-login': typeof authLoginCodeLoginRoute
  '/login/register': typeof authLoginRegisterRoute
  '/login/reset-pwd': typeof authLoginResetPwdRoute
  '/login/': typeof authLoginIndexRoute
  '/attendance/clock-in': typeof admindailyAttendanceClockInRoute
  '/attendance/leave': typeof admindailyAttendanceLeaveRouteWithChildren
  '/attendance/overtime': typeof admindailyAttendanceOvertimeRoute
  '/payroll/bonus-penalty': typeof admindailyPayrollBonusPenaltyRoute
  '/payroll/calculate': typeof admindailyPayrollCalculateRoute
  '/payroll/distribute': typeof admindailyPayrollDistributeRoute
  '/performance/evaluation': typeof admindevelopmentAndPerformancePerformanceEvaluationRoute
  '/performance/plans': typeof admindevelopmentAndPerformancePerformancePlansRoute
  '/training/plans': typeof admindevelopmentAndPerformanceTrainingPlansRoute
  '/training/records': typeof admindevelopmentAndPerformanceTrainingRecordsRoute
  '/employees/material': typeof adminpersonnelEmployeesMaterialRoute
  '/employees/offboarding': typeof adminpersonnelEmployeesOffboardingRoute
  '/employees/onboarding': typeof adminpersonnelEmployeesOnboardingRoute
  '/organization/chart': typeof adminpersonnelOrganizationChartRoute
  '/organization/departments': typeof adminpersonnelOrganizationDepartmentsRoute
  '/organization/roles': typeof adminpersonnelOrganizationRolesRoute
  '/iframe-page/$url': typeof adminBuiltinIframePageUrlRoute
  '/attendance/approval/$approvalId': typeof admindailyAttendanceApprovalApprovalIdRoute
  '/attendance/leave/$leaveId': typeof admindailyAttendanceLeaveLeaveIdRoute
  '/attendance/records/monthly': typeof admindailyAttendanceRecordsMonthlyRoute
  '/attendance/approval/': typeof admindailyAttendanceApprovalIndexRoute
  '/attendance/records/': typeof admindailyAttendanceRecordsIndexRoute
  '/attendance/approval/rules/$ruleId': typeof admindailyAttendanceApprovalRulesRuleIdRouteWithChildren
  '/attendance/approval/rules/new': typeof admindailyAttendanceApprovalRulesNewRoute
  '/attendance/approval/rules/$ruleId/edit': typeof admindailyAttendanceApprovalRulesRuleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof adminHomeLayoutRoute
  '/user-center': typeof adminUserCenterRoute
  '/login-out': typeof authLoginOutRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/attendance': typeof admindailyAttendanceLayoutRouteWithChildren
  '/payroll': typeof admindailyPayrollLayoutRouteWithChildren
  '/performance': typeof admindevelopmentAndPerformancePerformanceLayoutRouteWithChildren
  '/training': typeof admindevelopmentAndPerformanceTrainingLayoutRouteWithChildren
  '/employees': typeof adminpersonnelEmployeesLayoutRouteWithChildren
  '/organization': typeof adminpersonnelOrganizationLayoutRouteWithChildren
  '/notifications': typeof adminanalysisAndSettingNotificationsRoute
  '/reports': typeof adminanalysisAndSettingReportsRoute
  '/settings': typeof adminanalysisAndSettingSettingsRoute
  '/login/code-login': typeof authLoginCodeLoginRoute
  '/login/register': typeof authLoginRegisterRoute
  '/login/reset-pwd': typeof authLoginResetPwdRoute
  '/login': typeof authLoginIndexRoute
  '/attendance/clock-in': typeof admindailyAttendanceClockInRoute
  '/attendance/leave': typeof admindailyAttendanceLeaveRouteWithChildren
  '/attendance/overtime': typeof admindailyAttendanceOvertimeRoute
  '/payroll/bonus-penalty': typeof admindailyPayrollBonusPenaltyRoute
  '/payroll/calculate': typeof admindailyPayrollCalculateRoute
  '/payroll/distribute': typeof admindailyPayrollDistributeRoute
  '/performance/evaluation': typeof admindevelopmentAndPerformancePerformanceEvaluationRoute
  '/performance/plans': typeof admindevelopmentAndPerformancePerformancePlansRoute
  '/training/plans': typeof admindevelopmentAndPerformanceTrainingPlansRoute
  '/training/records': typeof admindevelopmentAndPerformanceTrainingRecordsRoute
  '/employees/material': typeof adminpersonnelEmployeesMaterialRoute
  '/employees/offboarding': typeof adminpersonnelEmployeesOffboardingRoute
  '/employees/onboarding': typeof adminpersonnelEmployeesOnboardingRoute
  '/organization/chart': typeof adminpersonnelOrganizationChartRoute
  '/organization/departments': typeof adminpersonnelOrganizationDepartmentsRoute
  '/organization/roles': typeof adminpersonnelOrganizationRolesRoute
  '/iframe-page/$url': typeof adminBuiltinIframePageUrlRoute
  '/attendance/approval/$approvalId': typeof admindailyAttendanceApprovalApprovalIdRoute
  '/attendance/leave/$leaveId': typeof admindailyAttendanceLeaveLeaveIdRoute
  '/attendance/records/monthly': typeof admindailyAttendanceRecordsMonthlyRoute
  '/attendance/approval': typeof admindailyAttendanceApprovalIndexRoute
  '/attendance/records': typeof admindailyAttendanceRecordsIndexRoute
  '/attendance/approval/rules/$ruleId': typeof admindailyAttendanceApprovalRulesRuleIdRouteWithChildren
  '/attendance/approval/rules/new': typeof admindailyAttendanceApprovalRulesNewRoute
  '/attendance/approval/rules/$ruleId/edit': typeof admindailyAttendanceApprovalRulesRuleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminLayoutRouteWithChildren
  '/(admin)/(analysisAndSetting)': typeof adminanalysisAndSettingLayoutRouteWithChildren
  '/(admin)/(daily)': typeof admindailyLayoutRouteWithChildren
  '/(admin)/(developmentAndPerformance)': typeof admindevelopmentAndPerformanceLayoutRouteWithChildren
  '/(admin)/(personnel)': typeof adminpersonnelLayoutRouteWithChildren
  '/(admin)/home': typeof adminHomeLayoutRoute
  '/(auth)/login': typeof authLoginLayoutRouteWithChildren
  '/(admin)/user-center': typeof adminUserCenterRoute
  '/(auth)/login-out': typeof authLoginOutRoute
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(admin)/(daily)/attendance': typeof admindailyAttendanceLayoutRouteWithChildren
  '/(admin)/(daily)/payroll': typeof admindailyPayrollLayoutRouteWithChildren
  '/(admin)/(developmentAndPerformance)/performance': typeof admindevelopmentAndPerformancePerformanceLayoutRouteWithChildren
  '/(admin)/(developmentAndPerformance)/training': typeof admindevelopmentAndPerformanceTrainingLayoutRouteWithChildren
  '/(admin)/(personnel)/employees': typeof adminpersonnelEmployeesLayoutRouteWithChildren
  '/(admin)/(personnel)/organization': typeof adminpersonnelOrganizationLayoutRouteWithChildren
  '/(admin)/(analysisAndSetting)/notifications': typeof adminanalysisAndSettingNotificationsRoute
  '/(admin)/(analysisAndSetting)/reports': typeof adminanalysisAndSettingReportsRoute
  '/(admin)/(analysisAndSetting)/settings': typeof adminanalysisAndSettingSettingsRoute
  '/(auth)/login/code-login': typeof authLoginCodeLoginRoute
  '/(auth)/login/register': typeof authLoginRegisterRoute
  '/(auth)/login/reset-pwd': typeof authLoginResetPwdRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(admin)/(daily)/attendance/clock-in': typeof admindailyAttendanceClockInRoute
  '/(admin)/(daily)/attendance/leave': typeof admindailyAttendanceLeaveRouteWithChildren
  '/(admin)/(daily)/attendance/overtime': typeof admindailyAttendanceOvertimeRoute
  '/(admin)/(daily)/payroll/bonus-penalty': typeof admindailyPayrollBonusPenaltyRoute
  '/(admin)/(daily)/payroll/calculate': typeof admindailyPayrollCalculateRoute
  '/(admin)/(daily)/payroll/distribute': typeof admindailyPayrollDistributeRoute
  '/(admin)/(developmentAndPerformance)/performance/evaluation': typeof admindevelopmentAndPerformancePerformanceEvaluationRoute
  '/(admin)/(developmentAndPerformance)/performance/plans': typeof admindevelopmentAndPerformancePerformancePlansRoute
  '/(admin)/(developmentAndPerformance)/training/plans': typeof admindevelopmentAndPerformanceTrainingPlansRoute
  '/(admin)/(developmentAndPerformance)/training/records': typeof admindevelopmentAndPerformanceTrainingRecordsRoute
  '/(admin)/(personnel)/employees/material': typeof adminpersonnelEmployeesMaterialRoute
  '/(admin)/(personnel)/employees/offboarding': typeof adminpersonnelEmployeesOffboardingRoute
  '/(admin)/(personnel)/employees/onboarding': typeof adminpersonnelEmployeesOnboardingRoute
  '/(admin)/(personnel)/organization/chart': typeof adminpersonnelOrganizationChartRoute
  '/(admin)/(personnel)/organization/departments': typeof adminpersonnelOrganizationDepartmentsRoute
  '/(admin)/(personnel)/organization/roles': typeof adminpersonnelOrganizationRolesRoute
  '/(admin)/_builtin/iframe-page/$url': typeof adminBuiltinIframePageUrlRoute
  '/(admin)/(daily)/attendance/approval/$approvalId': typeof admindailyAttendanceApprovalApprovalIdRoute
  '/(admin)/(daily)/attendance/leave/$leaveId': typeof admindailyAttendanceLeaveLeaveIdRoute
  '/(admin)/(daily)/attendance/records/monthly': typeof admindailyAttendanceRecordsMonthlyRoute
  '/(admin)/(daily)/attendance/approval/': typeof admindailyAttendanceApprovalIndexRoute
  '/(admin)/(daily)/attendance/records/': typeof admindailyAttendanceRecordsIndexRoute
  '/(admin)/(daily)/attendance/approval/rules/$ruleId': typeof admindailyAttendanceApprovalRulesRuleIdRouteWithChildren
  '/(admin)/(daily)/attendance/approval/rules/new': typeof admindailyAttendanceApprovalRulesNewRoute
  '/(admin)/(daily)/attendance/approval/rules/$ruleId/edit': typeof admindailyAttendanceApprovalRulesRuleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/user-center'
    | '/login-out'
    | '/403'
    | '/404'
    | '/500'
    | '/attendance'
    | '/payroll'
    | '/performance'
    | '/training'
    | '/employees'
    | '/organization'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/login/code-login'
    | '/login/register'
    | '/login/reset-pwd'
    | '/login/'
    | '/attendance/clock-in'
    | '/attendance/leave'
    | '/attendance/overtime'
    | '/payroll/bonus-penalty'
    | '/payroll/calculate'
    | '/payroll/distribute'
    | '/performance/evaluation'
    | '/performance/plans'
    | '/training/plans'
    | '/training/records'
    | '/employees/material'
    | '/employees/offboarding'
    | '/employees/onboarding'
    | '/organization/chart'
    | '/organization/departments'
    | '/organization/roles'
    | '/iframe-page/$url'
    | '/attendance/approval/$approvalId'
    | '/attendance/leave/$leaveId'
    | '/attendance/records/monthly'
    | '/attendance/approval/'
    | '/attendance/records/'
    | '/attendance/approval/rules/$ruleId'
    | '/attendance/approval/rules/new'
    | '/attendance/approval/rules/$ruleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/user-center'
    | '/login-out'
    | '/403'
    | '/404'
    | '/500'
    | '/attendance'
    | '/payroll'
    | '/performance'
    | '/training'
    | '/employees'
    | '/organization'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/login/code-login'
    | '/login/register'
    | '/login/reset-pwd'
    | '/login'
    | '/attendance/clock-in'
    | '/attendance/leave'
    | '/attendance/overtime'
    | '/payroll/bonus-penalty'
    | '/payroll/calculate'
    | '/payroll/distribute'
    | '/performance/evaluation'
    | '/performance/plans'
    | '/training/plans'
    | '/training/records'
    | '/employees/material'
    | '/employees/offboarding'
    | '/employees/onboarding'
    | '/organization/chart'
    | '/organization/departments'
    | '/organization/roles'
    | '/iframe-page/$url'
    | '/attendance/approval/$approvalId'
    | '/attendance/leave/$leaveId'
    | '/attendance/records/monthly'
    | '/attendance/approval'
    | '/attendance/records'
    | '/attendance/approval/rules/$ruleId'
    | '/attendance/approval/rules/new'
    | '/attendance/approval/rules/$ruleId/edit'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/(admin)/(analysisAndSetting)'
    | '/(admin)/(daily)'
    | '/(admin)/(developmentAndPerformance)'
    | '/(admin)/(personnel)'
    | '/(admin)/home'
    | '/(auth)/login'
    | '/(admin)/user-center'
    | '/(auth)/login-out'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(admin)/(daily)/attendance'
    | '/(admin)/(daily)/payroll'
    | '/(admin)/(developmentAndPerformance)/performance'
    | '/(admin)/(developmentAndPerformance)/training'
    | '/(admin)/(personnel)/employees'
    | '/(admin)/(personnel)/organization'
    | '/(admin)/(analysisAndSetting)/notifications'
    | '/(admin)/(analysisAndSetting)/reports'
    | '/(admin)/(analysisAndSetting)/settings'
    | '/(auth)/login/code-login'
    | '/(auth)/login/register'
    | '/(auth)/login/reset-pwd'
    | '/(auth)/login/'
    | '/(admin)/(daily)/attendance/clock-in'
    | '/(admin)/(daily)/attendance/leave'
    | '/(admin)/(daily)/attendance/overtime'
    | '/(admin)/(daily)/payroll/bonus-penalty'
    | '/(admin)/(daily)/payroll/calculate'
    | '/(admin)/(daily)/payroll/distribute'
    | '/(admin)/(developmentAndPerformance)/performance/evaluation'
    | '/(admin)/(developmentAndPerformance)/performance/plans'
    | '/(admin)/(developmentAndPerformance)/training/plans'
    | '/(admin)/(developmentAndPerformance)/training/records'
    | '/(admin)/(personnel)/employees/material'
    | '/(admin)/(personnel)/employees/offboarding'
    | '/(admin)/(personnel)/employees/onboarding'
    | '/(admin)/(personnel)/organization/chart'
    | '/(admin)/(personnel)/organization/departments'
    | '/(admin)/(personnel)/organization/roles'
    | '/(admin)/_builtin/iframe-page/$url'
    | '/(admin)/(daily)/attendance/approval/$approvalId'
    | '/(admin)/(daily)/attendance/leave/$leaveId'
    | '/(admin)/(daily)/attendance/records/monthly'
    | '/(admin)/(daily)/attendance/approval/'
    | '/(admin)/(daily)/attendance/records/'
    | '/(admin)/(daily)/attendance/approval/rules/$ruleId'
    | '/(admin)/(daily)/attendance/approval/rules/new'
    | '/(admin)/(daily)/attendance/approval/rules/$ruleId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  authLoginLayoutRoute: typeof authLoginLayoutRouteWithChildren
  authLoginOutRoute: typeof authLoginOutRoute
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login-out': {
      id: '/(auth)/login-out'
      path: '/login-out'
      fullPath: '/login-out'
      preLoaderRoute: typeof authLoginOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/user-center': {
      id: '/(admin)/user-center'
      path: '/user-center'
      fullPath: '/user-center'
      preLoaderRoute: typeof adminUserCenterRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/home': {
      id: '/(admin)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof adminHomeLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/(personnel)': {
      id: '/(admin)/(personnel)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminpersonnelLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/(developmentAndPerformance)': {
      id: '/(admin)/(developmentAndPerformance)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof admindevelopmentAndPerformanceLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/(daily)': {
      id: '/(admin)/(daily)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof admindailyLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/(analysisAndSetting)': {
      id: '/(admin)/(analysisAndSetting)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminanalysisAndSettingLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(auth)/login/reset-pwd': {
      id: '/(auth)/login/reset-pwd'
      path: '/reset-pwd'
      fullPath: '/login/reset-pwd'
      preLoaderRoute: typeof authLoginResetPwdRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(auth)/login/register': {
      id: '/(auth)/login/register'
      path: '/register'
      fullPath: '/login/register'
      preLoaderRoute: typeof authLoginRegisterRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(auth)/login/code-login': {
      id: '/(auth)/login/code-login'
      path: '/code-login'
      fullPath: '/login/code-login'
      preLoaderRoute: typeof authLoginCodeLoginRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(admin)/(analysisAndSetting)/settings': {
      id: '/(admin)/(analysisAndSetting)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof adminanalysisAndSettingSettingsRouteImport
      parentRoute: typeof adminanalysisAndSettingLayoutRoute
    }
    '/(admin)/(analysisAndSetting)/reports': {
      id: '/(admin)/(analysisAndSetting)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof adminanalysisAndSettingReportsRouteImport
      parentRoute: typeof adminanalysisAndSettingLayoutRoute
    }
    '/(admin)/(analysisAndSetting)/notifications': {
      id: '/(admin)/(analysisAndSetting)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof adminanalysisAndSettingNotificationsRouteImport
      parentRoute: typeof adminanalysisAndSettingLayoutRoute
    }
    '/(admin)/(personnel)/organization': {
      id: '/(admin)/(personnel)/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof adminpersonnelOrganizationLayoutRouteImport
      parentRoute: typeof adminpersonnelLayoutRoute
    }
    '/(admin)/(personnel)/employees': {
      id: '/(admin)/(personnel)/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof adminpersonnelEmployeesLayoutRouteImport
      parentRoute: typeof adminpersonnelLayoutRoute
    }
    '/(admin)/(developmentAndPerformance)/training': {
      id: '/(admin)/(developmentAndPerformance)/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof admindevelopmentAndPerformanceTrainingLayoutRouteImport
      parentRoute: typeof admindevelopmentAndPerformanceLayoutRoute
    }
    '/(admin)/(developmentAndPerformance)/performance': {
      id: '/(admin)/(developmentAndPerformance)/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof admindevelopmentAndPerformancePerformanceLayoutRouteImport
      parentRoute: typeof admindevelopmentAndPerformanceLayoutRoute
    }
    '/(admin)/(daily)/payroll': {
      id: '/(admin)/(daily)/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof admindailyPayrollLayoutRouteImport
      parentRoute: typeof admindailyLayoutRoute
    }
    '/(admin)/(daily)/attendance': {
      id: '/(admin)/(daily)/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof admindailyAttendanceLayoutRouteImport
      parentRoute: typeof admindailyLayoutRoute
    }
    '/(admin)/_builtin/iframe-page/$url': {
      id: '/(admin)/_builtin/iframe-page/$url'
      path: '/iframe-page/$url'
      fullPath: '/iframe-page/$url'
      preLoaderRoute: typeof adminBuiltinIframePageUrlRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/(personnel)/organization/roles': {
      id: '/(admin)/(personnel)/organization/roles'
      path: '/roles'
      fullPath: '/organization/roles'
      preLoaderRoute: typeof adminpersonnelOrganizationRolesRouteImport
      parentRoute: typeof adminpersonnelOrganizationLayoutRoute
    }
    '/(admin)/(personnel)/organization/departments': {
      id: '/(admin)/(personnel)/organization/departments'
      path: '/departments'
      fullPath: '/organization/departments'
      preLoaderRoute: typeof adminpersonnelOrganizationDepartmentsRouteImport
      parentRoute: typeof adminpersonnelOrganizationLayoutRoute
    }
    '/(admin)/(personnel)/organization/chart': {
      id: '/(admin)/(personnel)/organization/chart'
      path: '/chart'
      fullPath: '/organization/chart'
      preLoaderRoute: typeof adminpersonnelOrganizationChartRouteImport
      parentRoute: typeof adminpersonnelOrganizationLayoutRoute
    }
    '/(admin)/(personnel)/employees/onboarding': {
      id: '/(admin)/(personnel)/employees/onboarding'
      path: '/onboarding'
      fullPath: '/employees/onboarding'
      preLoaderRoute: typeof adminpersonnelEmployeesOnboardingRouteImport
      parentRoute: typeof adminpersonnelEmployeesLayoutRoute
    }
    '/(admin)/(personnel)/employees/offboarding': {
      id: '/(admin)/(personnel)/employees/offboarding'
      path: '/offboarding'
      fullPath: '/employees/offboarding'
      preLoaderRoute: typeof adminpersonnelEmployeesOffboardingRouteImport
      parentRoute: typeof adminpersonnelEmployeesLayoutRoute
    }
    '/(admin)/(personnel)/employees/material': {
      id: '/(admin)/(personnel)/employees/material'
      path: '/material'
      fullPath: '/employees/material'
      preLoaderRoute: typeof adminpersonnelEmployeesMaterialRouteImport
      parentRoute: typeof adminpersonnelEmployeesLayoutRoute
    }
    '/(admin)/(developmentAndPerformance)/training/records': {
      id: '/(admin)/(developmentAndPerformance)/training/records'
      path: '/records'
      fullPath: '/training/records'
      preLoaderRoute: typeof admindevelopmentAndPerformanceTrainingRecordsRouteImport
      parentRoute: typeof admindevelopmentAndPerformanceTrainingLayoutRoute
    }
    '/(admin)/(developmentAndPerformance)/training/plans': {
      id: '/(admin)/(developmentAndPerformance)/training/plans'
      path: '/plans'
      fullPath: '/training/plans'
      preLoaderRoute: typeof admindevelopmentAndPerformanceTrainingPlansRouteImport
      parentRoute: typeof admindevelopmentAndPerformanceTrainingLayoutRoute
    }
    '/(admin)/(developmentAndPerformance)/performance/plans': {
      id: '/(admin)/(developmentAndPerformance)/performance/plans'
      path: '/plans'
      fullPath: '/performance/plans'
      preLoaderRoute: typeof admindevelopmentAndPerformancePerformancePlansRouteImport
      parentRoute: typeof admindevelopmentAndPerformancePerformanceLayoutRoute
    }
    '/(admin)/(developmentAndPerformance)/performance/evaluation': {
      id: '/(admin)/(developmentAndPerformance)/performance/evaluation'
      path: '/evaluation'
      fullPath: '/performance/evaluation'
      preLoaderRoute: typeof admindevelopmentAndPerformancePerformanceEvaluationRouteImport
      parentRoute: typeof admindevelopmentAndPerformancePerformanceLayoutRoute
    }
    '/(admin)/(daily)/payroll/distribute': {
      id: '/(admin)/(daily)/payroll/distribute'
      path: '/distribute'
      fullPath: '/payroll/distribute'
      preLoaderRoute: typeof admindailyPayrollDistributeRouteImport
      parentRoute: typeof admindailyPayrollLayoutRoute
    }
    '/(admin)/(daily)/payroll/calculate': {
      id: '/(admin)/(daily)/payroll/calculate'
      path: '/calculate'
      fullPath: '/payroll/calculate'
      preLoaderRoute: typeof admindailyPayrollCalculateRouteImport
      parentRoute: typeof admindailyPayrollLayoutRoute
    }
    '/(admin)/(daily)/payroll/bonus-penalty': {
      id: '/(admin)/(daily)/payroll/bonus-penalty'
      path: '/bonus-penalty'
      fullPath: '/payroll/bonus-penalty'
      preLoaderRoute: typeof admindailyPayrollBonusPenaltyRouteImport
      parentRoute: typeof admindailyPayrollLayoutRoute
    }
    '/(admin)/(daily)/attendance/overtime': {
      id: '/(admin)/(daily)/attendance/overtime'
      path: '/overtime'
      fullPath: '/attendance/overtime'
      preLoaderRoute: typeof admindailyAttendanceOvertimeRouteImport
      parentRoute: typeof admindailyAttendanceLayoutRoute
    }
    '/(admin)/(daily)/attendance/leave': {
      id: '/(admin)/(daily)/attendance/leave'
      path: '/leave'
      fullPath: '/attendance/leave'
      preLoaderRoute: typeof admindailyAttendanceLeaveRouteImport
      parentRoute: typeof admindailyAttendanceLayoutRoute
    }
    '/(admin)/(daily)/attendance/clock-in': {
      id: '/(admin)/(daily)/attendance/clock-in'
      path: '/clock-in'
      fullPath: '/attendance/clock-in'
      preLoaderRoute: typeof admindailyAttendanceClockInRouteImport
      parentRoute: typeof admindailyAttendanceLayoutRoute
    }
    '/(admin)/(daily)/attendance/records/': {
      id: '/(admin)/(daily)/attendance/records/'
      path: '/records'
      fullPath: '/attendance/records/'
      preLoaderRoute: typeof admindailyAttendanceRecordsIndexRouteImport
      parentRoute: typeof admindailyAttendanceLayoutRoute
    }
    '/(admin)/(daily)/attendance/approval/': {
      id: '/(admin)/(daily)/attendance/approval/'
      path: '/approval'
      fullPath: '/attendance/approval/'
      preLoaderRoute: typeof admindailyAttendanceApprovalIndexRouteImport
      parentRoute: typeof admindailyAttendanceLayoutRoute
    }
    '/(admin)/(daily)/attendance/records/monthly': {
      id: '/(admin)/(daily)/attendance/records/monthly'
      path: '/records/monthly'
      fullPath: '/attendance/records/monthly'
      preLoaderRoute: typeof admindailyAttendanceRecordsMonthlyRouteImport
      parentRoute: typeof admindailyAttendanceLayoutRoute
    }
    '/(admin)/(daily)/attendance/leave/$leaveId': {
      id: '/(admin)/(daily)/attendance/leave/$leaveId'
      path: '/$leaveId'
      fullPath: '/attendance/leave/$leaveId'
      preLoaderRoute: typeof admindailyAttendanceLeaveLeaveIdRouteImport
      parentRoute: typeof admindailyAttendanceLeaveRoute
    }
    '/(admin)/(daily)/attendance/approval/$approvalId': {
      id: '/(admin)/(daily)/attendance/approval/$approvalId'
      path: '/approval/$approvalId'
      fullPath: '/attendance/approval/$approvalId'
      preLoaderRoute: typeof admindailyAttendanceApprovalApprovalIdRouteImport
      parentRoute: typeof admindailyAttendanceLayoutRoute
    }
    '/(admin)/(daily)/attendance/approval/rules/new': {
      id: '/(admin)/(daily)/attendance/approval/rules/new'
      path: '/approval/rules/new'
      fullPath: '/attendance/approval/rules/new'
      preLoaderRoute: typeof admindailyAttendanceApprovalRulesNewRouteImport
      parentRoute: typeof admindailyAttendanceLayoutRoute
    }
    '/(admin)/(daily)/attendance/approval/rules/$ruleId': {
      id: '/(admin)/(daily)/attendance/approval/rules/$ruleId'
      path: '/approval/rules/$ruleId'
      fullPath: '/attendance/approval/rules/$ruleId'
      preLoaderRoute: typeof admindailyAttendanceApprovalRulesRuleIdRouteImport
      parentRoute: typeof admindailyAttendanceLayoutRoute
    }
    '/(admin)/(daily)/attendance/approval/rules/$ruleId/edit': {
      id: '/(admin)/(daily)/attendance/approval/rules/$ruleId/edit'
      path: '/edit'
      fullPath: '/attendance/approval/rules/$ruleId/edit'
      preLoaderRoute: typeof admindailyAttendanceApprovalRulesRuleIdEditRouteImport
      parentRoute: typeof admindailyAttendanceApprovalRulesRuleIdRoute
    }
  }
}

interface adminanalysisAndSettingLayoutRouteChildren {
  adminanalysisAndSettingNotificationsRoute: typeof adminanalysisAndSettingNotificationsRoute
  adminanalysisAndSettingReportsRoute: typeof adminanalysisAndSettingReportsRoute
  adminanalysisAndSettingSettingsRoute: typeof adminanalysisAndSettingSettingsRoute
}

const adminanalysisAndSettingLayoutRouteChildren: adminanalysisAndSettingLayoutRouteChildren =
  {
    adminanalysisAndSettingNotificationsRoute:
      adminanalysisAndSettingNotificationsRoute,
    adminanalysisAndSettingReportsRoute: adminanalysisAndSettingReportsRoute,
    adminanalysisAndSettingSettingsRoute: adminanalysisAndSettingSettingsRoute,
  }

const adminanalysisAndSettingLayoutRouteWithChildren =
  adminanalysisAndSettingLayoutRoute._addFileChildren(
    adminanalysisAndSettingLayoutRouteChildren,
  )

interface admindailyAttendanceLeaveRouteChildren {
  admindailyAttendanceLeaveLeaveIdRoute: typeof admindailyAttendanceLeaveLeaveIdRoute
}

const admindailyAttendanceLeaveRouteChildren: admindailyAttendanceLeaveRouteChildren =
  {
    admindailyAttendanceLeaveLeaveIdRoute:
      admindailyAttendanceLeaveLeaveIdRoute,
  }

const admindailyAttendanceLeaveRouteWithChildren =
  admindailyAttendanceLeaveRoute._addFileChildren(
    admindailyAttendanceLeaveRouteChildren,
  )

interface admindailyAttendanceApprovalRulesRuleIdRouteChildren {
  admindailyAttendanceApprovalRulesRuleIdEditRoute: typeof admindailyAttendanceApprovalRulesRuleIdEditRoute
}

const admindailyAttendanceApprovalRulesRuleIdRouteChildren: admindailyAttendanceApprovalRulesRuleIdRouteChildren =
  {
    admindailyAttendanceApprovalRulesRuleIdEditRoute:
      admindailyAttendanceApprovalRulesRuleIdEditRoute,
  }

const admindailyAttendanceApprovalRulesRuleIdRouteWithChildren =
  admindailyAttendanceApprovalRulesRuleIdRoute._addFileChildren(
    admindailyAttendanceApprovalRulesRuleIdRouteChildren,
  )

interface admindailyAttendanceLayoutRouteChildren {
  admindailyAttendanceClockInRoute: typeof admindailyAttendanceClockInRoute
  admindailyAttendanceLeaveRoute: typeof admindailyAttendanceLeaveRouteWithChildren
  admindailyAttendanceOvertimeRoute: typeof admindailyAttendanceOvertimeRoute
  admindailyAttendanceApprovalApprovalIdRoute: typeof admindailyAttendanceApprovalApprovalIdRoute
  admindailyAttendanceRecordsMonthlyRoute: typeof admindailyAttendanceRecordsMonthlyRoute
  admindailyAttendanceApprovalIndexRoute: typeof admindailyAttendanceApprovalIndexRoute
  admindailyAttendanceRecordsIndexRoute: typeof admindailyAttendanceRecordsIndexRoute
  admindailyAttendanceApprovalRulesRuleIdRoute: typeof admindailyAttendanceApprovalRulesRuleIdRouteWithChildren
  admindailyAttendanceApprovalRulesNewRoute: typeof admindailyAttendanceApprovalRulesNewRoute
}

const admindailyAttendanceLayoutRouteChildren: admindailyAttendanceLayoutRouteChildren =
  {
    admindailyAttendanceClockInRoute: admindailyAttendanceClockInRoute,
    admindailyAttendanceLeaveRoute: admindailyAttendanceLeaveRouteWithChildren,
    admindailyAttendanceOvertimeRoute: admindailyAttendanceOvertimeRoute,
    admindailyAttendanceApprovalApprovalIdRoute:
      admindailyAttendanceApprovalApprovalIdRoute,
    admindailyAttendanceRecordsMonthlyRoute:
      admindailyAttendanceRecordsMonthlyRoute,
    admindailyAttendanceApprovalIndexRoute:
      admindailyAttendanceApprovalIndexRoute,
    admindailyAttendanceRecordsIndexRoute:
      admindailyAttendanceRecordsIndexRoute,
    admindailyAttendanceApprovalRulesRuleIdRoute:
      admindailyAttendanceApprovalRulesRuleIdRouteWithChildren,
    admindailyAttendanceApprovalRulesNewRoute:
      admindailyAttendanceApprovalRulesNewRoute,
  }

const admindailyAttendanceLayoutRouteWithChildren =
  admindailyAttendanceLayoutRoute._addFileChildren(
    admindailyAttendanceLayoutRouteChildren,
  )

interface admindailyPayrollLayoutRouteChildren {
  admindailyPayrollBonusPenaltyRoute: typeof admindailyPayrollBonusPenaltyRoute
  admindailyPayrollCalculateRoute: typeof admindailyPayrollCalculateRoute
  admindailyPayrollDistributeRoute: typeof admindailyPayrollDistributeRoute
}

const admindailyPayrollLayoutRouteChildren: admindailyPayrollLayoutRouteChildren =
  {
    admindailyPayrollBonusPenaltyRoute: admindailyPayrollBonusPenaltyRoute,
    admindailyPayrollCalculateRoute: admindailyPayrollCalculateRoute,
    admindailyPayrollDistributeRoute: admindailyPayrollDistributeRoute,
  }

const admindailyPayrollLayoutRouteWithChildren =
  admindailyPayrollLayoutRoute._addFileChildren(
    admindailyPayrollLayoutRouteChildren,
  )

interface admindailyLayoutRouteChildren {
  admindailyAttendanceLayoutRoute: typeof admindailyAttendanceLayoutRouteWithChildren
  admindailyPayrollLayoutRoute: typeof admindailyPayrollLayoutRouteWithChildren
}

const admindailyLayoutRouteChildren: admindailyLayoutRouteChildren = {
  admindailyAttendanceLayoutRoute: admindailyAttendanceLayoutRouteWithChildren,
  admindailyPayrollLayoutRoute: admindailyPayrollLayoutRouteWithChildren,
}

const admindailyLayoutRouteWithChildren =
  admindailyLayoutRoute._addFileChildren(admindailyLayoutRouteChildren)

interface admindevelopmentAndPerformancePerformanceLayoutRouteChildren {
  admindevelopmentAndPerformancePerformanceEvaluationRoute: typeof admindevelopmentAndPerformancePerformanceEvaluationRoute
  admindevelopmentAndPerformancePerformancePlansRoute: typeof admindevelopmentAndPerformancePerformancePlansRoute
}

const admindevelopmentAndPerformancePerformanceLayoutRouteChildren: admindevelopmentAndPerformancePerformanceLayoutRouteChildren =
  {
    admindevelopmentAndPerformancePerformanceEvaluationRoute:
      admindevelopmentAndPerformancePerformanceEvaluationRoute,
    admindevelopmentAndPerformancePerformancePlansRoute:
      admindevelopmentAndPerformancePerformancePlansRoute,
  }

const admindevelopmentAndPerformancePerformanceLayoutRouteWithChildren =
  admindevelopmentAndPerformancePerformanceLayoutRoute._addFileChildren(
    admindevelopmentAndPerformancePerformanceLayoutRouteChildren,
  )

interface admindevelopmentAndPerformanceTrainingLayoutRouteChildren {
  admindevelopmentAndPerformanceTrainingPlansRoute: typeof admindevelopmentAndPerformanceTrainingPlansRoute
  admindevelopmentAndPerformanceTrainingRecordsRoute: typeof admindevelopmentAndPerformanceTrainingRecordsRoute
}

const admindevelopmentAndPerformanceTrainingLayoutRouteChildren: admindevelopmentAndPerformanceTrainingLayoutRouteChildren =
  {
    admindevelopmentAndPerformanceTrainingPlansRoute:
      admindevelopmentAndPerformanceTrainingPlansRoute,
    admindevelopmentAndPerformanceTrainingRecordsRoute:
      admindevelopmentAndPerformanceTrainingRecordsRoute,
  }

const admindevelopmentAndPerformanceTrainingLayoutRouteWithChildren =
  admindevelopmentAndPerformanceTrainingLayoutRoute._addFileChildren(
    admindevelopmentAndPerformanceTrainingLayoutRouteChildren,
  )

interface admindevelopmentAndPerformanceLayoutRouteChildren {
  admindevelopmentAndPerformancePerformanceLayoutRoute: typeof admindevelopmentAndPerformancePerformanceLayoutRouteWithChildren
  admindevelopmentAndPerformanceTrainingLayoutRoute: typeof admindevelopmentAndPerformanceTrainingLayoutRouteWithChildren
}

const admindevelopmentAndPerformanceLayoutRouteChildren: admindevelopmentAndPerformanceLayoutRouteChildren =
  {
    admindevelopmentAndPerformancePerformanceLayoutRoute:
      admindevelopmentAndPerformancePerformanceLayoutRouteWithChildren,
    admindevelopmentAndPerformanceTrainingLayoutRoute:
      admindevelopmentAndPerformanceTrainingLayoutRouteWithChildren,
  }

const admindevelopmentAndPerformanceLayoutRouteWithChildren =
  admindevelopmentAndPerformanceLayoutRoute._addFileChildren(
    admindevelopmentAndPerformanceLayoutRouteChildren,
  )

interface adminpersonnelEmployeesLayoutRouteChildren {
  adminpersonnelEmployeesMaterialRoute: typeof adminpersonnelEmployeesMaterialRoute
  adminpersonnelEmployeesOffboardingRoute: typeof adminpersonnelEmployeesOffboardingRoute
  adminpersonnelEmployeesOnboardingRoute: typeof adminpersonnelEmployeesOnboardingRoute
}

const adminpersonnelEmployeesLayoutRouteChildren: adminpersonnelEmployeesLayoutRouteChildren =
  {
    adminpersonnelEmployeesMaterialRoute: adminpersonnelEmployeesMaterialRoute,
    adminpersonnelEmployeesOffboardingRoute:
      adminpersonnelEmployeesOffboardingRoute,
    adminpersonnelEmployeesOnboardingRoute:
      adminpersonnelEmployeesOnboardingRoute,
  }

const adminpersonnelEmployeesLayoutRouteWithChildren =
  adminpersonnelEmployeesLayoutRoute._addFileChildren(
    adminpersonnelEmployeesLayoutRouteChildren,
  )

interface adminpersonnelOrganizationLayoutRouteChildren {
  adminpersonnelOrganizationChartRoute: typeof adminpersonnelOrganizationChartRoute
  adminpersonnelOrganizationDepartmentsRoute: typeof adminpersonnelOrganizationDepartmentsRoute
  adminpersonnelOrganizationRolesRoute: typeof adminpersonnelOrganizationRolesRoute
}

const adminpersonnelOrganizationLayoutRouteChildren: adminpersonnelOrganizationLayoutRouteChildren =
  {
    adminpersonnelOrganizationChartRoute: adminpersonnelOrganizationChartRoute,
    adminpersonnelOrganizationDepartmentsRoute:
      adminpersonnelOrganizationDepartmentsRoute,
    adminpersonnelOrganizationRolesRoute: adminpersonnelOrganizationRolesRoute,
  }

const adminpersonnelOrganizationLayoutRouteWithChildren =
  adminpersonnelOrganizationLayoutRoute._addFileChildren(
    adminpersonnelOrganizationLayoutRouteChildren,
  )

interface adminpersonnelLayoutRouteChildren {
  adminpersonnelEmployeesLayoutRoute: typeof adminpersonnelEmployeesLayoutRouteWithChildren
  adminpersonnelOrganizationLayoutRoute: typeof adminpersonnelOrganizationLayoutRouteWithChildren
}

const adminpersonnelLayoutRouteChildren: adminpersonnelLayoutRouteChildren = {
  adminpersonnelEmployeesLayoutRoute:
    adminpersonnelEmployeesLayoutRouteWithChildren,
  adminpersonnelOrganizationLayoutRoute:
    adminpersonnelOrganizationLayoutRouteWithChildren,
}

const adminpersonnelLayoutRouteWithChildren =
  adminpersonnelLayoutRoute._addFileChildren(adminpersonnelLayoutRouteChildren)

interface adminLayoutRouteChildren {
  adminanalysisAndSettingLayoutRoute: typeof adminanalysisAndSettingLayoutRouteWithChildren
  admindailyLayoutRoute: typeof admindailyLayoutRouteWithChildren
  admindevelopmentAndPerformanceLayoutRoute: typeof admindevelopmentAndPerformanceLayoutRouteWithChildren
  adminpersonnelLayoutRoute: typeof adminpersonnelLayoutRouteWithChildren
  adminHomeLayoutRoute: typeof adminHomeLayoutRoute
  adminUserCenterRoute: typeof adminUserCenterRoute
  adminBuiltinIframePageUrlRoute: typeof adminBuiltinIframePageUrlRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminanalysisAndSettingLayoutRoute:
    adminanalysisAndSettingLayoutRouteWithChildren,
  admindailyLayoutRoute: admindailyLayoutRouteWithChildren,
  admindevelopmentAndPerformanceLayoutRoute:
    admindevelopmentAndPerformanceLayoutRouteWithChildren,
  adminpersonnelLayoutRoute: adminpersonnelLayoutRouteWithChildren,
  adminHomeLayoutRoute: adminHomeLayoutRoute,
  adminUserCenterRoute: adminUserCenterRoute,
  adminBuiltinIframePageUrlRoute: adminBuiltinIframePageUrlRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface authLoginLayoutRouteChildren {
  authLoginCodeLoginRoute: typeof authLoginCodeLoginRoute
  authLoginRegisterRoute: typeof authLoginRegisterRoute
  authLoginResetPwdRoute: typeof authLoginResetPwdRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const authLoginLayoutRouteChildren: authLoginLayoutRouteChildren = {
  authLoginCodeLoginRoute: authLoginCodeLoginRoute,
  authLoginRegisterRoute: authLoginRegisterRoute,
  authLoginResetPwdRoute: authLoginResetPwdRoute,
  authLoginIndexRoute: authLoginIndexRoute,
}

const authLoginLayoutRouteWithChildren = authLoginLayoutRoute._addFileChildren(
  authLoginLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  authLoginLayoutRoute: authLoginLayoutRouteWithChildren,
  authLoginOutRoute: authLoginOutRoute,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
