import { AuthProvider } from "@/contexts/AuthContext";
import { decodeJwt } from "jose";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import Layout from "./components/Layout";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = await cookies();

  const language = cookiesStore.get("GO_TECH_LANGUAGE")?.value || "zh-TW";

  const tokenExtists = cookiesStore.has("GO_TECH_AUTH_TOKEN");
  let user: User | null = null;
  if (tokenExtists) {
    const token = cookiesStore.get("GO_TECH_AUTH_TOKEN")!.value;
    const payload = decodeJwt(token) as User;

    user = payload;
  }

  return (
    <html lang={language}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialUser={user}>
          <Layout>{children}</Layout>
        </AuthProvider>
      </body>
    </html>
  );
}
